### ISSUE TITLE
Acquisition tab does not show data, keeps loading

### ISSUE THREAD

**Issue by Artdinamica1** [PrestaShop/ps-project-metrics#41]
Hello, we have the module installed but in the acquisition tab it does not show data, it remains as if it were loading, can you tell us what is happening?
![Screenshot_20](https://github.com/PrestaShop/ps-project-metrics/assets/158151459/63138016-3b45-4a68-8e1b-ea202e29af96)

**Comment by matks** [comment]
Hello @Artdinamica1 I am sorry there is a confusion 😅 this repository is not the ps_metrics repository and we are not the ps_metrics team.

This repository is a Symfony 5 application that collects and display data for project maintainer team.

In order to get help with ps_metrics team, you need to reach out to PrestaShop company support https://prestashop.com/contact/

I close this issue 😉 as it's not the right place
